---
title: "Calculate Frequencies"
format: pdf
editor: visual
---

```{r load packages}
if(!require(readr)){install.packages('readr')}
library(readr)
if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse) 
if(!require(car)){install.packages('car')}
library(car) 
```

```{r set working directory}
#Arielle's working directory
setwd("/Users/pmt4073/Desktop/LSMH/R Scripts/LGBTQ ED Treatment Barriers") #this is how you set the working directory in a basic R script

#Kade's working directory

getwd()
```

```{r import and clean data}
combined_frequencies <- read_csv("Data/combined_frequencies.csv", col_types = cols(.default = "c"))
all_data <- read_csv("Data/all_data.csv", col_types = cols(.default = "c"))

#Merge demographics etc with coding 
combined_frequencies <- combined_frequencies %>%
  left_join(all_data, by = "Participant_ID") %>% 
  select(-"...1") #not sure what this is so dropping it

#Code used to make gender_group previously for RCT:
#gender_cols <- missingness_handled %>% 
#  dplyr::select(starts_with("b_dem_gender_")) %>% 
#  names()
#cis_cols   <- c("b_dem_gender_1", "b_dem_gender_2")
#trans_cols <- setdiff(gender_cols, cis_cols)
#missingness_handled <- missingness_handled %>%
#  mutate(
#    gender_group = case_when(
#      if_any(all_of(trans_cols), ~ .x == 1) ~ "trans", #adds trans label if any trans categories selected
#      if_any(all_of(cis_cols), ~ .x == 1) ~ "cis")) #adds cis label if a cis category was selected and if no trans label was applied above

#Make necessary variables factors
combined_frequencies <- combined_frequencies %>% 
  mutate(
    across(
      c(
        starts_with("b_dem_sexuality"), 
        starts_with("b_dem_sex"), 
        starts_with("b_current"), 
        starts_with("b_past"), 
        starts_with("b_unmet"), 
        starts_with("b_hunger"), 
        starts_with("b_dem_gender"), 
        starts_with("b_dem_race"),
        starts_with("gender_group")
      ),
      as.factor
    )
  )

#Make all necessary variables numeric
combined_frequencies <- combined_frequencies %>%
  mutate(
    across(
      c(
        Code_1:Code_11, 
        starts_with("b_dem_age"), 
        starts_with("b_edeq")
      ),
      as.numeric
    )
  )

#Add baseline EDEQ means
combined_frequencies <- combined_frequencies %>%
  mutate(
    b_edeq_dietary_restraint = (b_edeq_1 + b_edeq_2 + b_edeq_3) / 3,
    b_edeq_preoccupation_eatingconcern = (b_edeq_4 + b_edeq_5 + b_edeq_6) / 3,
    b_edeq_overvaluation = (b_edeq_7 + b_edeq_8 + b_edeq_9 + b_edeq_10) / 4,
    b_edeq_global = (b_edeq_dietary_restraint + b_edeq_preoccupation_eatingconcern + b_edeq_overvaluation) / 3
  )
```

```{r count number of barriers endorsed per participant}
combined_frequencies <- combined_frequencies %>%
  rowwise() %>%
  mutate(barrier_count = sum(c_across(Code_1:Code_11), na.rm = TRUE)) %>%
  ungroup()

#Calculate mean and standard deviation of new barrier_count variable
combined_frequencies %>% 
  summarize(mean(barrier_count), 
            sd(barrier_count))

combined_frequencies %>% 
  group_by(gender_group) %>% 
  summarize(mean(barrier_count), 
            sd(barrier_count))
```

```{r count frequnecy of each code endorsed}
npercent_each_barrier <- combined_frequencies %>%
  summarise(
    across(starts_with("Code_"),
           list(
             count = ~sum(. == 1),
             percent = ~sum(. == 1) / nrow(combined_frequencies) * 100
           )))

npercent_each_barrier_grouped <- combined_frequencies %>%
  group_by(gender_group) %>% 
  summarise(
    across(starts_with("Code_"),
           list(
             count = ~sum(. == 1),
             percent = ~sum(. == 1) / nrow(combined_frequencies) * 100
           )))
```

Kade - you can check out how I calculated the same variables for the RCT here: https://github.com/isaacahuvia/body-neutrality-ssi/blob/main/RCT/2_Analysis.Rmd 
(just command F to find the demographics chunk)

```{r demographics}
#Example:
all_data %>% #dataframe
  count(dem_ethnicity) %>% #the demographics variable
  mutate(percent = (n / sum(n))*100)
```

```{r contingency tables and test for differences}
code1_table <- table(
  response = combined_frequencies$Code_1,
  gender_group = combined_frequencies$gender_group
)
chisq.test(code1_table)$expected < 5
chisq.test(code1_table)$expected
code1_test <- chisq.test(code1_table)
code1_test


code2_table <- table(
  response = combined_frequencies$Code_2,
  gender_group = combined_frequencies$gender_group
)
chisq.test(code2_table)$expected
chisq.test(code1_table)$expected < 5
#Violation - cannot do chi square
code2_test <- fisher.test(code2_table)
code2_test
```
```{r BH correction}
p_values <- data.frame(
  code = c("code1", "code2"....),
  p_value = c(
    code1_test$p.value,
    code2_test$p.value,
    ....
  ))

p_values$p_adjusted <- p.adjust(chi_pvals$p_value, method = "BH")
p_values
```

```{r independent t test}
#First levene's test to see if we should do student's or welch's 
leveneTest(barrier_count ~ gender_group, data = combined_frequencies)
#No significant difference between variance, so can use student's (var.equal = T)

t.test(barrier_count ~ gender_group,
  data = combined_frequencies,
  var.equal = TRUE)
```


```{r}
#Consider something like a correlation heatmap to see which codes are combined the most
```
